apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-chat-app
  template:
    metadata:
      labels:
        app: flask-chat-app
    spec:
      containers:
        - name: flask-chat-app
          image: us-central1-docker.pkg.dev/software-da/flask-chat-repo/flask-chat-app:v2
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
