apiVersion: v1
kind: Service
metadata:
  name: flask-chat-service
  labels:
    app: flask-chat-app
spec:
  selector:
    app: flask-chat-app  
  ports:
    - protocol: TCP
      port: 5000  # Exposed service port
      targetPort: 5000  # Flask app listens on this port
  type: LoadBalancer  # Expose the service externally
